---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'Il portafoglio digitale BlueXP consente di gestire e monitorare le licenze BlueXP acquistate da NetApp (BYOL), gli abbonamenti BlueXP Marketplace e NetApp Keystone.' 
---
= Scopri di più sul portafoglio digitale BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il portafoglio digitale BlueXP consente di gestire e monitorare le licenze BlueXP acquistate da NetApp (BYOL), gli abbonamenti BlueXP Marketplace e NetApp Keystone.



== Caratteristiche

* Gestione delle licenze basate su capacità e su nodo per Cloud Volumes ONTAP
* Aggiungere e gestire le licenze per i servizi dati BlueXP
* Gestisci gli abbonamenti per PAYGO e i contratti annuali associati al tuo account BlueXP e con Astra Control
* Gestisci i servizi di iscrizione Keystone per l'utilizzo con i cluster Cloud Volumes ONTAP e ONTAP on-premise e richiede le modifiche alla capacità impegnata
* Visualizza le informazioni sullo stato dei contratti hardware e software per i cluster ONTAP on-premise




== Servizi supportati

Il Digital Wallet di BlueXP consente di gestire le licenze per i seguenti servizi:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup e recovery"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Disaster recovery"^] (Solo BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Protezione ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Cluster ONTAP on-premise"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering"^]



TIP: Il Digital Wallet di BlueXP  ti consente inoltre di gestire le licenze per la classificazione BlueXP . Tuttavia, la classificazione BlueXP  è ora disponibile come funzionalità di base all'interno di BlueXP  senza costi aggiuntivi. Non è più necessario disporre di una licenza o di un abbonamento. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Scopri di più sulla classificazione BlueXP"^]
