---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'Il portafoglio digitale BlueXP consente di gestire e monitorare le licenze BlueXP acquistate da NetApp (BYOL), gli abbonamenti BlueXP Marketplace e NetApp Keystone.' 
---
= Scopri di più sul portafoglio digitale BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il Digital Wallet di BlueXP  ti consente di gestire e monitorare le licenze BlueXP  acquistate da NetApp (BYOL), le iscrizioni al marketplace dei servizi dati di BlueXP  (NetApp Cloud Volumes ONTAP incluso) e NetApp Keystone.



== Modalità di visualizzazione di licenze e abbonamenti nel portafoglio digitale

Le licenze e gli abbonamenti vengono visualizzati automaticamente nel portafoglio digitale quando l'account BlueXP  utilizzato per l'abbonamento è anche un account del sito di supporto NetApp. Se hai utilizzato un account BlueXP  non associato al tuo account NSS (NetApp Support Site), dovrai aggiungere e aggiornare manualmente le licenze e non vedrai che l'utilizzo, la capacità e altri dettagli cambiano.


NOTE: Per visualizzare le informazioni relative all'abbonamento nel portafoglio digitale, è necessario installare un connettore. È inoltre necessario un connettore per visualizzare le licenze dei nodi per Cloud Volumes ONTAP.

Nel frattempo, BlueXP interroga automaticamente il servizio di licenza di NetApp per ottenere informazioni sulle licenze associate al tuo account NetApp Support Site. In assenza di errori, BlueXP aggiunge automaticamente le licenze al portafoglio digitale.

Se BlueXP  non è in grado di aggiungere la licenza, è necessario aggiungerla manualmente al portafoglio digitale. Ad esempio, se l'account utente BlueXP  non è associato all'account del sito di supporto NetApp, sarà necessario aggiungere le licenze.

Dopo aver acquistato una licenza dal rappresentante di vendita NetApp, NetApp invia un'e-mail con il numero di serie e i dettagli aggiuntivi della licenza. Per aggiungere o aggiornare la rispettiva licenza nel portafoglio digitale, è necessario disporre di tale numero di serie.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["Scopri come aggiungere il tuo account del sito di supporto NetApp alle credenziali utente di BlueXP "^].



== Servizi supportati

Il Digital Wallet di BlueXP  ti consente di gestire licenze e iscrizioni per i seguenti servizi:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup e recovery"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Disaster recovery"^] (Solo BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Protezione ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Cluster ONTAP on-premise"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering"^]

