---
settings:
  name: BlueXP digital wallet
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti del portafoglio digitale BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sul portafoglio digitale BlueXP
      url: "/concept-digital-wallet.html"
  - title: Utilizza il portafoglio digitale BlueXP
    entries:
    - title: Utilizzare il dashboard Panoramica
      url: "/task-homepage.html"
    - title: Gestire le licenze
      entries:
      - title: Gestire le licenze dei servizi dati
        url: "/task-manage-data-services-licenses.html"
      - title: Gestire le licenze per Cloud Volumes ONTAP
        entries:
        - title: Licenze basate sulla capacità per Cloud Volumes ONTAP
          url: "/task-manage-capacity-licenses.html"
        - title: Licenze basate su nodi per Cloud Volumes ONTAP
          url: "/task-manage-node-based-licenses.html"
    - title: Gestire gli abbonamenti Marketplace
      url: "/task-manage-subscriptions.html"
    - title: Gestire gli abbonamenti Keystone
      url: "/task-manage-keystone.html"
    - title: Gestisci le licenze per ONTAP on-premise
      url: "/task-manage-on-prem-clusters.html"
    - title: Conoscenza e supporto
      entries:
      - title: Registrati per ricevere assistenza
        url: "/task-support-registration.html"
      - title: Richiedi assistenza
        url: "/task-get-help.html"
    - title: Note legali
      url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
