= Nuova dashboard Panoramica
:allow-uri-read: 


Il portafoglio digitale di BlueXP  è stato riprogettato per garantire facilità d'uso e ora offre funzionalità aggiuntive di gestione delle licenze e delle sottoscrizioni.



=== Nuova dashboard Panoramica

La home page del portafoglio digitale dispone di una dashboard aggiornata delle licenze NetApp e delle iscrizioni al marketplace, con la possibilità di analizzare in dettaglio servizi, tipi di licenza e azioni richieste.



=== Configurazione delle sottoscrizioni alle credenziali

Il Digital Wallet di BlueXP  consente ora di configurare le iscrizioni per le credenziali del provider. In genere, questa operazione viene eseguita quando si sottoscrive per la prima volta un abbonamento a Marketplace o un contratto annuale. In precedenza, la modifica delle credenziali dell'abbonamento poteva essere effettuata solo nella pagina credenziali.



=== Associazione delle sottoscrizioni alle organizzazioni

Ora puoi aggiornare l'organizzazione a cui è associato un abbonamento direttamente dal portafoglio digitale.



=== Gestione delle licenze di Cloud Volume ONTAP

Ora è possibile gestire le licenze Cloud Volumes ONTAP tramite la home page o la scheda *licenze servizio dati*. Utilizzare la scheda *Marketplace sottoscrizioni* per visualizzare le informazioni relative all'abbonamento.
